# Generated by Django 5.1.4 on 2024-12-28 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='daily_img/')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Daily Text',
                'verbose_name_plural': 'Daily Texts',
                'ordering': ['-date_created'],
            },
        ),
    ]
