# Generated by Django 5.1.3 on 2024-12-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='userProfile/default.jpg', upload_to='userProfile/'),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('position', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('specialties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.speciality')),
            ],
            bases=('accounts.userprofile',),
        ),
    ]
