# Generated by Django 5.1.4 on 2024-12-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Expenses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position',
            field=models.CharField(default='عضو هیئت علمی دانشگاه جهرم', max_length=255),
        ),
    ]
