# Generated by Django 5.1.4 on 2024-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_specialist_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_modir',
            field=models.BooleanField(default=False),
        ),
    ]
