# Generated by Django 5.1.4 on 2024-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_is_modir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='userProfile/default.png', null=True, upload_to='userProfile/'),
        ),
    ]
